### ISSUE TITLE
TypeError: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by bensedik** [qjadud1994/Korea-license-plate-Generator#1]
Hi,
Can you @[qjadud1994](/qjadud1994) help me in resolving this issue:
CRNN-Keras/Korean-license-plate-Generator/Generator_original.py", line 119, in Type_1
    for i, Iter in enumerate(range(num)):
TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by pendex900x** [comment]
Did you solve it? How?
